modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Tritium"
credits = ""
authors = "QianMo_ProMax,ZCRAFT,KSmc_brigade"
logoFile = "assets/${mod_id}/icon.png"
description = '''
An all-in-one optimization module dedicated to optimizing client-side rendering and server-side stability and fluency.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.13,1.14)"
ordering = "NONE"
side = "BOTH"
